apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cache-app
  template:
    metadata:
      labels:
        app: cache-app
    spec:
      containers:
        - name: cache-container
          image: naghammasalmeh/cache
          env:
          - name: DJANGO_SETTINGS_MODULE
            value: "cache_api.settings"
          ports:
            - containerPort: 8080