apiVersion: v1
kind: Service
metadata:
  name: cache-service
spec:
  selector:
    app: cache-app  # The label selector to match Pods belonging to your application
  ports:
    - protocol: TCP
      port: 80      # The port on which the Service will listen
      targetPort: 8080  # The port on the Pods to forward the traffic to
  type: LoadBalancer