version: '3.8'

services:
  web:
    image: app
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    links:
      - db
    environment:
        - DJANGO_SETTINGS_MODULE=cache_api.settings
        - MONGO_HOST=mongodb
    depends_on:
      - migration
  
  db:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: naghammasalmah
        MONGO_INITDB_ROOT_PASSWORD: fXVkOITNj4fqwoLc
      ports:
        - 27017:27017
      hostname: db
      volumes:
        - mongodb_data_container:/data/db
  
  migration:
    build: .
    image: app
    command: python manage.py migrate
    links:
      - db
    depends_on:
      - make_migrations
  
  make_migrations:
    build: .
    image: app
    command: python manage.py makemigrations
    links:
      - db
    depends_on:
      - db

volumes:
  mongodb_data_container: