version: '3.8'

services:
  web:
    image: app
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    links:
      - db
    environment:
        - DJANGO_SETTINGS_MODULE=cache_api.settings
        - MONGO_HOST=mongo
  
  db:
      image: mongo
      restart: always
      ports:
        - 27017:27017
      hostname: db
      volumes:
        - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: